"""Every probe in this directory must be findable from tests/README.md.

    python3 tests/index.py            # print the index
    python3 tests/index.py --write    # write it into tests/README.md
    python3 tests/index.py --check    # fail if what is there is out of date

THE SUITE OUTGREW ITS OWN MAP. tests/README.md is a narrative - it explains the
lanes, the visual pages, and a dozen subjects in depth - and it was written when
there were a dozen probes. There are about ninety now, and SIXTY-NINE of them
were named nowhere in it. Nothing failed, because nothing checks prose; what it
costs is a reader, who cannot tell whether the thing they are about to write a
probe for already has one. That is how tests/ss_axis.py came to sit outside
run.sh for a whole session while three other files measured the same property.

So: one line per probe, generated from the file's own first line of docstring,
with the lane it runs in. Generated because a hand-written index of ninety files
is a list that is wrong within a week, and CHECKED because a generated one
nobody regenerates is the same list.

The lane comes from run.sh, so a probe that is in no lane says `tool` - which is
right for the benches and the by-hand demonstrations, and is a question worth
asking about anything else. Adding a probe and not running it is the failure
this makes visible.
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = "<!-- INDEX: generated by tests/index.py, do not edit by hand -->"
END = "<!-- END INDEX -->"

# The scaffolding, which is not a probe: a helper nobody runs on its own, and
# the make_* fixtures, which are inputs.
HELPERS = {"cdp", "probe_js", "draw_diff", "build", "index"}


def lane_of(run, name):
    for lane, pat in (("node", r"for f in ([a-z_0-9 ]+); do"),
                      ("ui", r"UI=\((.*?)\)"),
                      ("gpu", r"for t in (gpu_recolour.*?); do")):
        m = re.search(pat, run, re.S)
        if m and name in m.group(1).split():
            return lane
    # ...the ones run by name rather than from a list
    if re.search(r"run_probe %s\b" % re.escape(name), run):
        return "ui"
    if re.search(r"python3 tests/%s\.py|node tests/%s\.js" % (name, name), run):
        return "node"
    return "tool"


def summary(path):
    s = open(path, encoding="utf-8").read()
    if path.endswith(".py"):
        m = re.match(r'\s*(?:"""|\'\'\')(.*)', s)
        # ...and a one-line docstring closes on the same line, so the quotes
        # come with it
        return re.sub(r'("""|\'\'\')\s*$', "", m.group(1)).strip() if m else ""
    # A .js check opens with a block comment or a line of //, and not always on
    # line one - tests/gpu_prototype.js starts with its require. So: the first
    # comment line in the file that says something, which is what a reader
    # scrolling to the top would take as the summary too.
    m = re.match(r"\s*/\*+\s*\n?\s*\*?\s*(.*)", s)
    if m and m.group(1).strip():
        return m.group(1).strip().rstrip("*/").strip()
    for line in s.split("\n")[:40]:
        t = line.strip()
        if t.startswith("//") and len(t) > 4:
            return t[2:].strip()
    return ""


def table():
    run = open(os.path.join(ROOT, "tests", "run.sh"), encoding="utf-8").read()
    rows = []
    for path in sorted(glob.glob(os.path.join(ROOT, "tests", "*.py"))
                       + glob.glob(os.path.join(ROOT, "tests", "*.js"))):
        name = os.path.basename(path)
        stem = name.rsplit(".", 1)[0]
        if stem in HELPERS or stem.startswith("make_"):
            continue
        what = summary(path)
        # a table cell cannot hold a pipe, and a first line rarely needs one
        rows.append((name, lane_of(run, stem), what.replace("|", "/")))
    out = [START, "", "| Probe | Lane | What it answers |", "| --- | --- | --- |"]
    for name, lane, what in rows:
        out.append(f"| `{name}` | {lane} | {what} |")
    out += ["", END]
    return "\n".join(out)


def main():
    readme = os.path.join(ROOT, "tests", "README.md")
    body = table()
    if "--write" in sys.argv:
        s = open(readme, encoding="utf-8").read()
        if START in s and END in s:
            s = s[:s.index(START)] + body + s[s.index(END) + len(END):]
        else:
            anchor = "\n## Assertions"
            at = s.index(anchor)
            s = s[:at] + "\n## Every probe, and which lane runs it\n\n" + body + "\n" + s[at:]
        open(readme, "w", encoding="utf-8").write(s)
        print("wrote the index into tests/README.md")
        return 0
    if "--check" in sys.argv:
        s = open(readme, encoding="utf-8").read()
        if START not in s or END not in s:
            print("FAIL: tests/README.md has no generated index."
                  " Run: python3 tests/index.py --write")
            return 1
        have = s[s.index(START):s.index(END) + len(END)]
        if have.strip() != body.strip():
            hl = have.strip().split("\n")
            bl = body.strip().split("\n")
            gone = [x for x in hl if x not in bl]
            new = [x for x in bl if x not in hl]
            print("FAIL: the probe index in tests/README.md is out of date."
                  " Run: python3 tests/index.py --write")
            for x in new[:6]:
                print("  missing: " + x)
            for x in gone[:6]:
                print("  stale:   " + x)
            return 1
        print("index: every probe is in tests/README.md, with its lane")
        return 0
    print(body)
    return 0


sys.exit(main())
