"""Every repo path named in a comment or a doc must exist.

    python3 tests/paths.py

THE COMMENTS ARE THE MAP, AND THE MAP WENT STALE THE MOMENT THE FILES MOVED.
Splitting the renderer renamed sixteen files, and 236 mentions of the old names
survived in prose that nothing checks: `viewer-mol.js` in a hundred comments
that meant `core/mol.js`, error messages telling a reader to look in
`web/utils.js` for a symbol now in `src/io/parse.js`, a header in tools/extract_part.py
that still WROTE its output to `py2Dmol/resources/viewer-mol-<name>.js`. Tests
pass either way, which is exactly the problem: a wrong pointer costs a reader
the same as a wrong line of code and nothing ever fails.

So this reads every tracked text file, pulls out anything shaped like a path
into this repo, and checks it is there. Not clever - the shape is
`<top-level dir>/<something>.<ext>` - but a rename cannot be finished while it
fails, which is the whole point.

ALLOWED names a mention that is CORRECT while pointing at nothing:

  * an assertion that a file is GONE (tests/align.js checks the second copy of
    TM-align has not come back);
  * a sentence about the past, where the old name is the subject;
  * a path in a DIFFERENT repository (../aoe, ../foldjs).

Each entry carries its reason. An allowlist that grows without one is how this
check stops meaning anything.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# EVERY TEXT EXTENSION THE TREE HAS, and this list is the second load-bearing
# one. `.mjs` was missing, so tests/vendor_tmalign.mjs kept pointing at the
# align file's old home through the reorganisation and this check saw nothing -
# the align test caught it instead, by regenerating TM-align from a path that
# had ceased to exist.
TEXT = ('.md', '.py', '.js', '.mjs', '.sh', '.html', '.css', '.yml', '.yaml',
        '.ipynb', '.txt', '.toml', '.cfg')
# THE TOP-LEVEL DIRECTORIES, AND THIS LIST IS LOAD-BEARING. Renaming web/ to
# src/ without adding it here took the scan from 651 mentions to 417 and it
# still said "ok" - a check that passes by finding nothing, which is the shape
# half the bugs in this repo have had. The floor below is what catches that.
PATH = re.compile(r'(?<![\w.$/-])((?:py2Dmol|src|tests|tools)/[\w./-]*'
                  r'[\w-]\.(?:js|py|html|css|md|sh))')

ALLOWED = {
    # ...a file whose ABSENCE is the assertion
    ('tests/align.js', 'py2Dmol/resources/tmalign.js'):
        'asserts the second copy of TM-align has not come back',
    # ...and a path in ANOTHER repository that happens to share our new root.
    # `src/` was `web/` until the reorganisation, and the geometry's credit to
    # CIRPIN-web names a file of theirs under the same prefix - not ours, and
    # never was. (Spelled in pieces so this comment does not trip the scan.)
    ('src/cartoon/geom.js', 'src/' + 'trace3d.js'):
        "CIRPIN-web's file, credited in the port note - a different repository",
    # ...and this file talks about the rename it exists to catch, so it names a
    # dead file in its own docstring. Every OTHER path it mentions is still
    # checked, which was confirmed by breaking one and watching this fail.
    ('tests/paths.py', 'py2Dmol/resources/tmalign.js'):
        'the allowlist entry above quotes it',
}

# docs/technical_readme.md is 1,992 lines dated 2025-12-12 and says of itself that it
# is "out of date and is not maintained". Its paths are stale because ALL of it
# is - the line counts, the file tree, the function inventory - and rewriting the
# paths alone would make a stale document look current. It is excluded whole,
# and that is a decision to revisit by deleting or rewriting it, not by adding
# entries above.
SKIP_FILES = {'docs/technical_readme.md'}


def tracked():
    out = subprocess.run(['git', 'ls-files'], cwd=ROOT,
                         capture_output=True, text=True).stdout.split()
    return [f for f in out
            if f.endswith(TEXT) and '.min.js' not in f and f not in SKIP_FILES]


bad, allowed_used, n = [], set(), 0
for rel in tracked():
    try:
        lines = open(os.path.join(ROOT, rel)).read().split('\n')
    except (OSError, UnicodeDecodeError):
        continue
    for i, line in enumerate(lines, 1):
        for hit in dict.fromkeys(PATH.findall(line)):
            n += 1
            if os.path.exists(os.path.join(ROOT, hit)):
                continue
            # tests/out/ is generated by tests/build.py and is gitignored
            if hit.startswith('tests/out/'):
                continue
            if (rel, hit) in ALLOWED:
                allowed_used.add((rel, hit))
                continue
            bad.append(f'{rel}:{i} names {hit}, which does not exist')

print(f'{n} path mentions across {len(tracked())} files')

# ...and an allowlist entry that no longer matches anything is itself stale
for key in sorted(set(ALLOWED) - allowed_used):
    bad.append(f'ALLOWED has {key[0]} -> {key[1]}, which is no longer mentioned'
               ' there - drop the entry')

# ...and a FLOOR, not merely "more than zero". The tree has hundreds of these;
# a scan that suddenly finds a handful has stopped reading, not been tidied.
if n < 500:
    bad.append(f'only {n} path mentions found, and this tree has hundreds -'
               ' the regex has stopped matching a top-level directory, so most'
               ' of the tree is no longer being checked')

for b in bad:
    print('FAIL: ' + b)
print('ok' if not bad else f'{len(bad)} stale')
sys.exit(1 if bad else 0)
